### ISSUE TITLE
Share insights on handling layout reading order

### ISSUE THREAD

**Issue by mllife** [DS4SD/docling-core#13]
I am curious to understand your insights into the algorithm for creating the final markdown order based on layout predictions. Are you planning to add some ML model for this in future? How complex document layouts can be handled? It seems there is very limited research in this domain with open use license.

**Comment by PeterStaar-IBM** [comment]
@mllife Yes, it is there but a bit hidden in a cumbersome way. We are currently trying to first re-visit the types in this package (too much tied to legacy) and then clean up this topic.

stay tuned!

**Comment by PeterStaar-IBM** [comment]
@mllife This is now resolved in v2. A good function to look at is here: https://github.com/DS4SD/docling-core/blob/main/docling_core/types/doc/document.py#L1427
