### ISSUE TITLE
Remove dependency on `pyproject-toml`

### ISSUE THREAD

**Issue by tiran** [DS4SD/docling-core#28]
Would it be possible to drop dependency on `pyproject-toml`? According to the project's [PyPI page](https://pypi.org/project/pyproject-toml/#history), it is pre-alpha software that has not seen any release or [commit](https://github.com/pyproject-toml/pyproject-toml) since 2021.

We like to package Docling for [InstructLab](https://github.com/instructlab). The package is causing us some headache. It is depending on itself to build. We cannot bootstrap the package from sources.

Is the package actually used? I don't see an import or reference to the project outside of poetry dependency in `pyproject.toml` and the lock file.

**Comment by dolfim-ibm** [comment]
Definitely, @vagenas @ceberam can you please have a look?

**Comment by ceberam** [comment]
@tiran This package is indeed not used and not necessary. We will remove it ASAP.

**Comment by vagenas** [comment]
@tiran this has now been removed with [v1.6.1](https://pypi.org/project/docling-core/1.6.1/).

**Comment by tiran** [comment]
Wow, thank you for landing the fix in record time! Awesome work.
